### ISSUE TITLE
Lock discussions

### ISSUE THREAD

**Issue by JustArchi** [dessant/lock-threads#25]
I'd love to be able to utilize your (awesome!) lock-threads GitHub action in order to automatically lock the discussions in addition to issues and PR.

Is something like that planned?

```yaml
          discussion-lock-inactive-days: '365'
          discussion-exclude-created-before: ''
          discussion-exclude-labels: ''
          discussion-lock-labels: ''
          discussion-lock-comment: ''
          discussion-lock-reason: 'resolved'
```

Thank you in advance for considering it, I really appreciate your work on this project.
