### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by steveoh** [dessant/lock-threads#35]
This may be something we are experiencing based on the git commit history size of our repo or the amount of activity during our lock window, but this action is failing because it is exceeding github's rate limiting.

> You have exceeded a secondary rate limit. Please wait a few minutes before you try again

Can we slow this action down on it's usage of the github api to allow for larger/active repositories to function properly?

**Comment by dessant** [comment]
You could edit the `cron` property to reduce the frequency of scheduled runs: https://github.com/dessant/lock-threads#examples

Though the action is currently broken because of a GitHub regression, see this comment for details: https://github.com/dessant/lock-threads/pull/33#issuecomment-1153230324

We could intergrate a tool like this to handle rate limiting in the future: https://github.com/octokit/plugin-throttling.js

**Comment by steveoh** [comment]
This is run daily, `0 7 * * *`, so I don't think it's a frequency issue. I think throttling would be a great feature to add.

**Comment by steveoh** [comment]
Still a common issue for us. 

<img width="688" alt="image" src="https://user-images.githubusercontent.com/325813/189698840-90d99683-677b-4fd0-b283-90faa1283ce3.png">

**Comment by DaveSkender** [comment]
GitHub has some advise on how to actively handle the rate limit.  Some options:

- limit to one call per second
- adapt call frequency on error with `Retry-After: [delay]`

Ref: https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits

**Comment by bflad** [comment]
This cropped up for us as well on a relatively small issue/PR count repository:

> Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again.

The associated workflow configuration:

```yaml
name: 'Lock Threads'

on:
  schedule:
    - cron: '50 1 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ github.token }}
          issue-comment: >
            I'm going to lock this issue because it has been closed for _30 days_ ⏳. This helps our maintainers find and focus on the active issues.
            If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
          issue-inactive-days: '30'
          pr-comment: >
            I'm going to lock this pull request because it has been closed for _30 days_ ⏳. This helps our maintainers find and focus on the active contributions.
            If you have found a problem that seems related to this change, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
          pr-inactive-days: '30'
```

Over in some of my personal and my work's GitHub Actions written in JavaScript, they utilize GitHub's `@ockokit/plugin-throttling` package to handle retries and throttling logic.

NPM Package: https://www.npmjs.com/package/@octokit/plugin-throttling
Example Implementation: https://github.com/bflad/action-milestone-comment/blob/main/octokit.js
